name: CI/CD CAMS-F Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Flutter Web Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Terraform Init & Apply
      working-directory: ./terraform
      run: |
        terraform init
        terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Build Flutter Web
      working-directory: ./flutter_app
      run: flutter build web

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
