test.yml
name: Flutter Tests  

on: [push, pull_request]  

jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  
      - uses: subosito/flutter-action@v2  
        with:  
          flutter-version: '3.13.0'  
      - run: flutter pub get  
      - run: flutter test  